[release-v1.34] Backport some test fixes (#2107)
* Enable pending test case 5072 - registry import when image contains valid archived raw file (#1798)

For context, was disabled as part of:
https://github.com/kubevirt/containerized-data-importer/pull/1119#issuecomment-595205735
But seems to pass comfortably now on NFS as well.

Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

* Fix smartclone sometimes not triggering due to capicity not being reported. (#1844)

* Fix smartclone sometimes not triggering.
Updated tests to use a real image instead of data that is filled.

Signed-off-by: Alexander Wels <awels@redhat.com>

* Refactor getSnapshotClass into two functions

Signed-off-by: Alexander Wels <awels@redhat.com>

* Use constant instead of magic number for size.

Signed-off-by: Alexander Wels <awels@redhat.com>

* force bind for WFFC storage on tests.

Signed-off-by: Alexander Wels <awels@redhat.com>

* Updated based on comments.
Fixed failing functional test.

Signed-off-by: Alexander Wels <awels@redhat.com>

* Correct md5sum verification in tests (#1895)

* Correct target image verification

The md5 command now can fail when the path is wrong.
TinyCoreBlockMD5 const is corrected.

Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

* Correct image verification in tests

Correct image path for clone/transport tests.
Wait for source pvc to be ready.
Also correct TinyCoreBlockMD5

Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

* Commit write to disk in source-pvc filler pod (#1937)

Addresses a flake where the clone target DV is "Succeeded" and empty:
```bash
[WARN] error executing command ["/bin/sh" "-c" "md5sum /pvc/disk.img"], error: command terminated with exit code 1
INFO: stderr: [md5sum: /pvc/disk.img: No such file or directory]
```
What I believe happens here is that the filler pod is not committing writes and directly exiting after the `echo 1245 > disk.img`,
resulting in us cloning an empty pvc and doing a successfull job at it.
Did not see it fail at all with the `&& sync` addition.

Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

* Run imageio test deployment as root (#1931)

We see an error starting the deployment's server d/s:
```bash
[cnv-qe-jenkins@alex48-451-xzjsk-executor ocs-test]$ oc logs -f -n openshift-cnv imageio-deployment-f9bfff68-clbs2 imageiotest
Using configuration from /etc/pki/tls/openssl.cnf
...
  File "/ovirt-imageio/daemon/ovirt_imageio/uhttp.py", line 80, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
curl: (7) Couldn't connect to server
```
Running as root seems to solve it, and doesn't harm test integrity since it's a test-helper.

Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

Co-authored-by: Alexander Wels <awels@redhat.com>
Co-authored-by: Bartosz Rybacki <brybacki@redhat.com>