Run imageio test deployment as root (#1931)
We see an error starting the deployment's server d/s:
```bash
[cnv-qe-jenkins@alex48-451-xzjsk-executor ocs-test]$ oc logs -f -n openshift-cnv imageio-deployment-f9bfff68-clbs2 imageiotest
Using configuration from /etc/pki/tls/openssl.cnf
...
  File "/ovirt-imageio/daemon/ovirt_imageio/uhttp.py", line 80, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
curl: (7) Couldn't connect to server
```
Running as root seems to solve it, and doesn't harm test integrity since it's a test-helper.

Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>